[project]
name = "physics-exam-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "crewai>=0.22.5",
    "fpdf>=1.7.2",
]
